services:
  mysql:
    image: mysql:8.0
    container_name: mysql-webshop
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: webshop
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: