spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webshop?serverTimezone=UTC
    username: root
    password: DawoodMoosa4977
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ðŸ‘ˆ IMPORTANT (not create)
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
