spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webshop?serverTimezone=UTC
    username: root
    password: DawoodMoosa4977
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  web:
    resources:
      static-locations: file:/Users/utbnadham10/website/webshopapi/uploads/

  mvc:
    static-path-pattern: /uploads/**

app:
  upload-dir: /Users/utbnadahm10/website/webshopapi/uploads

